# Generated by Django 2.2.2 on 2019-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('assesment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assesment_subject', models.CharField(max_length=200)),
                ('assesment_date', models.DateField()),
                ('start_time', models.TimeField(help_text='24hrs format hh:mm:ss', null=True)),
                ('duration', models.TimeField(help_text='hh:mm', null=True)),
            ],
        ),
    ]
