# Generated by Django 2.2.2 on 2019-07-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='course_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Assesment.Course'),
            preserve_default=False,
        ),
    ]
