# Generated by Django 2.2.2 on 2019-07-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0003_auto_20190728_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='course_id',
        ),
    ]
