# Generated by Django 2.2.2 on 2019-07-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0004_remove_assesment_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assesment.Course'),
        ),
    ]
