# Generated by Django 2.2.2 on 2019-07-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0005_assesment_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(null=True)),
                ('building_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='assesment',
            name='assesment_subject',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deparment_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assesment.Room')),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assesment.Course')),
            ],
        ),
    ]
