# Generated by Django 2.2.2 on 2019-07-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0006_auto_20190728_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='assesment_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=200),
        ),
        migrations.AddField(
            model_name='assesment',
            name='full_marks',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='assesment',
            name='pass_marks',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assesment.Course')),
            ],
        ),
    ]
