# Generated by Django 2.2.2 on 2019-07-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0007_auto_20190728_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='assesment_day',
        ),
        migrations.RemoveField(
            model_name='department',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='course_id',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('BEX', 'BEX'), ('BCT', 'BCT'), ('BCE', 'BCE'), ('BME', 'BME'), ('BAE', 'BAE'), ('BEL', 'BEL')], default='BEX', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Assesment.Department'),
        ),
    ]
